{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Install modules"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: ray==2.9.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[client]==2.9.0) (2.9.0)\n",
      "Requirement already satisfied: click>=7.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (8.1.7)\n",
      "Requirement already satisfied: filelock in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (3.16.1)\n",
      "Requirement already satisfied: jsonschema in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (4.23.0)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (1.1.0)\n",
      "Requirement already satisfied: packaging in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (24.2)\n",
      "Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (5.28.3)\n",
      "Requirement already satisfied: pyyaml in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (6.0.2)\n",
      "Requirement already satisfied: aiosignal in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (1.3.1)\n",
      "Requirement already satisfied: frozenlist in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (1.5.0)\n",
      "Requirement already satisfied: requests in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[client]==2.9.0) (2.32.3)\n",
      "Requirement already satisfied: grpcio in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[client]==2.9.0) (1.67.1)\n",
      "Requirement already satisfied: attrs>=22.2.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[client]==2.9.0) (24.2.0)\n",
      "Requirement already satisfied: importlib-resources>=1.4.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[client]==2.9.0) (6.4.5)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[client]==2.9.0) (2023.12.1)\n",
      "Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[client]==2.9.0) (1.3.10)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[client]==2.9.0) (0.35.1)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[client]==2.9.0) (0.20.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[client]==2.9.0) (3.4.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[client]==2.9.0) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[client]==2.9.0) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[client]==2.9.0) (2024.8.30)\n",
      "Requirement already satisfied: zipp>=3.1.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema->ray==2.9.0->ray[client]==2.9.0) (3.20.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: ray==2.9.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (2.9.0)\n",
      "Requirement already satisfied: click>=7.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (8.1.7)\n",
      "Requirement already satisfied: filelock in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (3.16.1)\n",
      "Requirement already satisfied: jsonschema in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (4.23.0)\n",
      "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (1.1.0)\n",
      "Requirement already satisfied: packaging in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (24.2)\n",
      "Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (5.28.3)\n",
      "Requirement already satisfied: pyyaml in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (6.0.2)\n",
      "Requirement already satisfied: aiosignal in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (1.3.1)\n",
      "Requirement already satisfied: frozenlist in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (1.5.0)\n",
      "Requirement already satisfied: requests in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray==2.9.0->ray[serve]==2.9.0) (2.32.3)\n",
      "Requirement already satisfied: colorful in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.5.6)\n",
      "Requirement already satisfied: watchfiles in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.24.0)\n",
      "Requirement already satisfied: fastapi in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.115.5)\n",
      "Requirement already satisfied: aiorwlock in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (1.4.0)\n",
      "Requirement already satisfied: py-spy>=0.2.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.4.0)\n",
      "Requirement already satisfied: prometheus-client>=0.7.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.21.0)\n",
      "Requirement already satisfied: gpustat>=1.0.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (1.1.1)\n",
      "Requirement already satisfied: aiohttp>=3.7 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (3.10.10)\n",
      "Requirement already satisfied: smart-open in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (7.0.5)\n",
      "Requirement already satisfied: starlette in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.41.2)\n",
      "Requirement already satisfied: aiohttp-cors in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.7.0)\n",
      "Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (2.9.2)\n",
      "Requirement already satisfied: virtualenv<20.21.1,>=20.0.24 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (20.21.0)\n",
      "Requirement already satisfied: opencensus in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.11.4)\n",
      "Requirement already satisfied: uvicorn[standard] in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (0.32.0)\n",
      "Requirement already satisfied: grpcio>=1.32.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ray[serve]==2.9.0) (1.67.1)\n",
      "Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from aiohttp>=3.7->ray[serve]==2.9.0) (2.4.3)\n",
      "Requirement already satisfied: attrs>=17.3.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from aiohttp>=3.7->ray[serve]==2.9.0) (24.2.0)\n",
      "Requirement already satisfied: multidict<7.0,>=4.5 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from aiohttp>=3.7->ray[serve]==2.9.0) (6.1.0)\n",
      "Requirement already satisfied: yarl<2.0,>=1.12.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from aiohttp>=3.7->ray[serve]==2.9.0) (1.15.2)\n",
      "Requirement already satisfied: async-timeout<5.0,>=4.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from aiohttp>=3.7->ray[serve]==2.9.0) (4.0.3)\n",
      "Requirement already satisfied: nvidia-ml-py>=11.450.129 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from gpustat>=1.0.0->ray[serve]==2.9.0) (12.560.30)\n",
      "Requirement already satisfied: psutil>=5.6.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from gpustat>=1.0.0->ray[serve]==2.9.0) (6.1.0)\n",
      "Requirement already satisfied: blessed>=1.17.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from gpustat>=1.0.0->ray[serve]==2.9.0) (1.20.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[serve]==2.9.0) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.23.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[serve]==2.9.0) (2.23.4)\n",
      "Requirement already satisfied: typing-extensions>=4.6.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,<3->ray[serve]==2.9.0) (4.12.2)\n",
      "Requirement already satisfied: distlib<1,>=0.3.6 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from virtualenv<20.21.1,>=20.0.24->ray[serve]==2.9.0) (0.3.9)\n",
      "Requirement already satisfied: platformdirs<4,>=2.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from virtualenv<20.21.1,>=20.0.24->ray[serve]==2.9.0) (3.11.0)\n",
      "Requirement already satisfied: anyio<5,>=3.4.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from starlette->ray[serve]==2.9.0) (4.5.2)\n",
      "Requirement already satisfied: importlib-resources>=1.4.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[serve]==2.9.0) (6.4.5)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[serve]==2.9.0) (2023.12.1)\n",
      "Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[serve]==2.9.0) (1.3.10)\n",
      "Requirement already satisfied: referencing>=0.28.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[serve]==2.9.0) (0.35.1)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jsonschema->ray==2.9.0->ray[serve]==2.9.0) (0.20.1)\n",
      "Requirement already satisfied: opencensus-context>=0.1.3 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from opencensus->ray[serve]==2.9.0) (0.1.3)\n",
      "Requirement already satisfied: six~=1.16 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from opencensus->ray[serve]==2.9.0) (1.16.0)\n",
      "Requirement already satisfied: google-api-core<3.0.0,>=1.0.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from opencensus->ray[serve]==2.9.0) (2.23.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[serve]==2.9.0) (3.4.0)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[serve]==2.9.0) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[serve]==2.9.0) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->ray==2.9.0->ray[serve]==2.9.0) (2024.8.30)\n",
      "Requirement already satisfied: wrapt in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from smart-open->ray[serve]==2.9.0) (1.16.0)\n",
      "Requirement already satisfied: h11>=0.8 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from uvicorn[standard]; extra == \"serve\"->ray[serve]==2.9.0) (0.14.0)\n",
      "Requirement already satisfied: httptools>=0.5.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from uvicorn[standard]; extra == \"serve\"->ray[serve]==2.9.0) (0.6.4)\n",
      "Requirement already satisfied: python-dotenv>=0.13 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from uvicorn[standard]; extra == \"serve\"->ray[serve]==2.9.0) (1.0.1)\n",
      "Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from uvicorn[standard]; extra == \"serve\"->ray[serve]==2.9.0) (0.21.0)\n",
      "Requirement already satisfied: websockets>=10.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from uvicorn[standard]; extra == \"serve\"->ray[serve]==2.9.0) (13.1)\n",
      "Requirement already satisfied: sniffio>=1.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from anyio<5,>=3.4.0->starlette->ray[serve]==2.9.0) (1.3.1)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.2 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from anyio<5,>=3.4.0->starlette->ray[serve]==2.9.0) (1.2.2)\n",
      "Requirement already satisfied: wcwidth>=0.1.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from blessed>=1.17.1->gpustat>=1.0.0->ray[serve]==2.9.0) (0.2.13)\n",
      "Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[serve]==2.9.0) (1.65.0)\n",
      "Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[serve]==2.9.0) (1.25.0)\n",
      "Requirement already satisfied: google-auth<3.0.dev0,>=2.14.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from google-api-core<3.0.0,>=1.0.0->opencensus->ray[serve]==2.9.0) (2.36.0)\n",
      "Requirement already satisfied: zipp>=3.1.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from importlib-resources>=1.4.0->jsonschema->ray==2.9.0->ray[serve]==2.9.0) (3.20.2)\n",
      "Requirement already satisfied: propcache>=0.2.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from yarl<2.0,>=1.12.0->aiohttp>=3.7->ray[serve]==2.9.0) (0.2.0)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[serve]==2.9.0) (5.5.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[serve]==2.9.0) (0.4.1)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[serve]==2.9.0) (4.9)\n",
      "Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.dev0,>=2.14.1->google-api-core<3.0.0,>=1.0.0->opencensus->ray[serve]==2.9.0) (0.6.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: transformers in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (4.46.2)\n",
      "Requirement already satisfied: fastapi in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (0.115.5)\n",
      "Requirement already satisfied: starlette in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (0.41.2)\n",
      "Requirement already satisfied: filelock in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (3.16.1)\n",
      "Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (0.26.2)\n",
      "Requirement already satisfied: numpy>=1.17 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (1.24.4)\n",
      "Requirement already satisfied: packaging>=20.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (24.2)\n",
      "Requirement already satisfied: pyyaml>=5.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (6.0.2)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (2024.11.6)\n",
      "Requirement already satisfied: requests in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (2.32.3)\n",
      "Requirement already satisfied: safetensors>=0.4.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (0.4.5)\n",
      "Requirement already satisfied: tokenizers<0.21,>=0.20 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (0.20.3)\n",
      "Requirement already satisfied: tqdm>=4.27 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from transformers) (4.67.0)\n",
      "Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from fastapi) (2.9.2)\n",
      "Requirement already satisfied: typing-extensions>=4.8.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from fastapi) (4.12.2)\n",
      "Requirement already satisfied: anyio<5,>=3.4.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from starlette) (4.5.2)\n",
      "Requirement already satisfied: idna>=2.8 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from anyio<5,>=3.4.0->starlette) (3.10)\n",
      "Requirement already satisfied: sniffio>=1.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from anyio<5,>=3.4.0->starlette) (1.3.1)\n",
      "Requirement already satisfied: exceptiongroup>=1.0.2 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from anyio<5,>=3.4.0->starlette) (1.2.2)\n",
      "Requirement already satisfied: fsspec>=2023.5.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.10.0)\n",
      "Requirement already satisfied: annotated-types>=0.6.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (0.7.0)\n",
      "Requirement already satisfied: pydantic-core==2.23.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi) (2.23.4)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->transformers) (3.4.0)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->transformers) (2.2.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from requests->transformers) (2024.8.30)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: ipywidgets in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (8.1.5)\n",
      "Requirement already satisfied: comm>=0.1.3 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipywidgets) (0.2.2)\n",
      "Requirement already satisfied: ipython>=6.1.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipywidgets) (8.12.3)\n",
      "Requirement already satisfied: traitlets>=4.3.1 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipywidgets) (5.14.3)\n",
      "Requirement already satisfied: widgetsnbextension~=4.0.12 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipywidgets) (4.0.13)\n",
      "Requirement already satisfied: jupyterlab-widgets~=3.0.12 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipywidgets) (3.0.13)\n",
      "Requirement already satisfied: backcall in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.0)\n",
      "Requirement already satisfied: decorator in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (5.1.1)\n",
      "Requirement already satisfied: jedi>=0.16 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)\n",
      "Requirement already satisfied: matplotlib-inline in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)\n",
      "Requirement already satisfied: pickleshare in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.7.5)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.48)\n",
      "Requirement already satisfied: pygments>=2.4.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (2.18.0)\n",
      "Requirement already satisfied: stack-data in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)\n",
      "Requirement already satisfied: typing-extensions in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (4.12.2)\n",
      "Requirement already satisfied: pexpect>4.3 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)\n",
      "Requirement already satisfied: ptyprocess>=0.5 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)\n",
      "Requirement already satisfied: wcwidth in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets) (0.2.13)\n",
      "Requirement already satisfied: executing>=1.2.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.1.0)\n",
      "Requirement already satisfied: asttokens>=2.1.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (2.4.1)\n",
      "Requirement already satisfied: pure-eval in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from stack-data->ipython>=6.1.0->ipywidgets) (0.2.3)\n",
      "Requirement already satisfied: six>=1.12.0 in /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install -U \"ray[client]==2.9.0\"\n",
    "%pip install -U \"ray[serve]==2.9.0\"\n",
    "%pip install transformers fastapi starlette\n",
    "\n",
    "%pip install -U ipywidgets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2024-11-13 08:56:12,452\tINFO worker.py:1715 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8266 \u001b[39m\u001b[22m\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m INFO 2024-11-13 08:56:19,009 proxy 192.168.100.251 proxy.py:1128 - Proxy actor de8796fd9a7224e02b3c86e401000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=778018, ip=192.168.100.251, actor_id=de8796fd9a7224e02b3c86e401000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7c360014aee0>)\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=778018)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:56:22,232 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 5.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:56:22,233 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n"
     ]
    },
    {
     "ename": "RayActorError",
     "evalue": "The actor died unexpectedly before finishing this task.\n\tclass_name: ProxyActor\n\tactor_id: de8796fd9a7224e02b3c86e401000000\n\tpid: 778018\n\tname: SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43\n\tnamespace: serve\n\tip: 192.168.100.251\nThe actor is dead because it was killed by `ray.kill`.",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayActorError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[13], line 50\u001b[0m\n\u001b[1;32m     48\u001b[0m \u001b[38;5;66;03m# Bind and run the deployment\u001b[39;00m\n\u001b[1;32m     49\u001b[0m chatbot_app \u001b[38;5;241m=\u001b[39m Chatbot\u001b[38;5;241m.\u001b[39mbind(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mmicrosoft/DialoGPT-small\u001b[39m\u001b[38;5;124m\"\u001b[39m)  \u001b[38;5;66;03m# Replace with your model ID\u001b[39;00m\n\u001b[0;32m---> 50\u001b[0m \u001b[43mserve\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mrun\u001b[49m\u001b[43m(\u001b[49m\u001b[43mchatbot_app\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/api.py:498\u001b[0m, in \u001b[0;36mrun\u001b[0;34m(target, _blocking, host, port, name, route_prefix, logging_config)\u001b[0m\n\u001b[1;32m    491\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m host \u001b[38;5;241m!=\u001b[39m DEFAULT_HTTP_HOST \u001b[38;5;129;01mor\u001b[39;00m port \u001b[38;5;241m!=\u001b[39m DEFAULT_HTTP_PORT:\n\u001b[1;32m    492\u001b[0m     warnings\u001b[38;5;241m.\u001b[39mwarn(\n\u001b[1;32m    493\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mSpecifying host and port in `serve.run` is deprecated and will be \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    494\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mremoved in a future version. To specify custom HTTP options, use \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    495\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m`serve.start`.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    496\u001b[0m     )\n\u001b[0;32m--> 498\u001b[0m client \u001b[38;5;241m=\u001b[39m \u001b[43m_private_api\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mserve_start\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    499\u001b[0m \u001b[43m    \u001b[49m\u001b[43mhttp_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m{\u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mhost\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mhost\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mport\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[43mport\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mlocation\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m:\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mEveryNode\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m}\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    500\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    502\u001b[0m \u001b[38;5;66;03m# Record after Ray has been started.\u001b[39;00m\n\u001b[1;32m    503\u001b[0m ServeUsageTag\u001b[38;5;241m.\u001b[39mAPI_VERSION\u001b[38;5;241m.\u001b[39mrecord(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mv2\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "File \u001b[0;32m~/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/api.py:291\u001b[0m, in \u001b[0;36mserve_start\u001b[0;34m(http_options, grpc_options, global_logging_config, **kwargs)\u001b[0m\n\u001b[1;32m    288\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m RayServeException:\n\u001b[1;32m    289\u001b[0m     \u001b[38;5;28;01mpass\u001b[39;00m\n\u001b[0;32m--> 291\u001b[0m controller, controller_name \u001b[38;5;241m=\u001b[39m \u001b[43m_start_controller\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    292\u001b[0m \u001b[43m    \u001b[49m\u001b[43mhttp_options\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mgrpc_options\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mglobal_logging_config\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\n\u001b[1;32m    293\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    295\u001b[0m client \u001b[38;5;241m=\u001b[39m ServeControllerClient(\n\u001b[1;32m    296\u001b[0m     controller,\n\u001b[1;32m    297\u001b[0m     controller_name,\n\u001b[1;32m    298\u001b[0m )\n\u001b[1;32m    299\u001b[0m _set_global_client(client)\n",
      "File \u001b[0;32m~/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/api.py:175\u001b[0m, in \u001b[0;36m_start_controller\u001b[0;34m(http_options, grpc_options, global_logging_config, **kwargs)\u001b[0m\n\u001b[1;32m    173\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(proxy_handles) \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[1;32m    174\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 175\u001b[0m         \u001b[43mray\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    176\u001b[0m \u001b[43m            \u001b[49m\u001b[43m[\u001b[49m\u001b[43mhandle\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mready\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mremote\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mhandle\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mproxy_handles\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mvalues\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    177\u001b[0m \u001b[43m            \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mHTTP_PROXY_TIMEOUT\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    178\u001b[0m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    179\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m ray\u001b[38;5;241m.\u001b[39mexceptions\u001b[38;5;241m.\u001b[39mGetTimeoutError:\n\u001b[1;32m    180\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mTimeoutError\u001b[39;00m(\n\u001b[1;32m    181\u001b[0m             \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mHTTP proxies not available after \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mHTTP_PROXY_TIMEOUT\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124ms.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    182\u001b[0m         )\n",
      "File \u001b[0;32m~/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_private/auto_init_hook.py:22\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     19\u001b[0m \u001b[38;5;129m@wraps\u001b[39m(fn)\n\u001b[1;32m     20\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mauto_init_wrapper\u001b[39m(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m     21\u001b[0m     auto_init_ray()\n\u001b[0;32m---> 22\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfn\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_private/client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    101\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m \u001b[38;5;241m!=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minit\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;129;01mor\u001b[39;00m is_client_mode_enabled_by_default:\n\u001b[1;32m    102\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mgetattr\u001b[39m(ray, func\u001b[38;5;241m.\u001b[39m\u001b[38;5;18m__name__\u001b[39m)(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m--> 103\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfunc\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_private/worker.py:2626\u001b[0m, in \u001b[0;36mget\u001b[0;34m(object_refs, timeout)\u001b[0m\n\u001b[1;32m   2624\u001b[0m             \u001b[38;5;28;01mraise\u001b[39;00m value\u001b[38;5;241m.\u001b[39mas_instanceof_cause()\n\u001b[1;32m   2625\u001b[0m         \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m-> 2626\u001b[0m             \u001b[38;5;28;01mraise\u001b[39;00m value\n\u001b[1;32m   2628\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m is_individual_id:\n\u001b[1;32m   2629\u001b[0m     values \u001b[38;5;241m=\u001b[39m values[\u001b[38;5;241m0\u001b[39m]\n",
      "\u001b[0;31mRayActorError\u001b[0m: The actor died unexpectedly before finishing this task.\n\tclass_name: ProxyActor\n\tactor_id: de8796fd9a7224e02b3c86e401000000\n\tpid: 778018\n\tname: SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43\n\tnamespace: serve\n\tip: 192.168.100.251\nThe actor is dead because it was killed by `ray.kill`."
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m INFO 2024-11-13 08:56:24,629 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 8bcd42f7b11b6ef7cf2fbb5d01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=778146, ip=192.168.100.251, actor_id=8bcd42f7b11b6ef7cf2fbb5d01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7f0cf2109f10>)\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=778146)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:56:32,292 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 10.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:56:32,292 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m INFO 2024-11-13 08:56:33,964 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 893bc7fd2739d71f569a5fe401000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=778364, ip=192.168.100.251, actor_id=893bc7fd2739d71f569a5fe401000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x70481c24af10>)\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=778364)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:56:47,368 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 15.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:56:47,368 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m INFO 2024-11-13 08:56:49,137 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 12d9b9d0ee3c5452574a457f01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=778653, ip=192.168.100.251, actor_id=12d9b9d0ee3c5452574a457f01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x769e54cc9eb0>)\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=778653)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:57:07,442 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 20.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:57:07,443 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m INFO 2024-11-13 08:57:09,479 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 2bade6122cd8f3d22e55806a01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=779020, ip=192.168.100.251, actor_id=2bade6122cd8f3d22e55806a01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x77a7c204aeb0>)\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=779020)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:57:32,478 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 25.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:57:32,479 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m INFO 2024-11-13 08:57:34,071 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 311fdf9ac032c3ac33d998cb01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=779533, ip=192.168.100.251, actor_id=311fdf9ac032c3ac33d998cb01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x77ca4174ef40>)\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=779533)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:58:02,579 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 30.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:58:02,579 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m INFO 2024-11-13 08:58:03,970 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 1279f7717ff5fbab8b70cef101000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=780231, ip=192.168.100.251, actor_id=1279f7717ff5fbab8b70cef101000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7f8a720cae80>)\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=780231)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:58:37,602 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 35.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:58:37,603 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m INFO 2024-11-13 08:58:39,843 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 04dc7168243ec75bb2649bd301000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=781418, ip=192.168.100.251, actor_id=04dc7168243ec75bb2649bd301000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7dea07fcef10>)\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=781418)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 08:59:17,646 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 40.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 08:59:17,646 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m INFO 2024-11-13 08:59:19,496 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 13d69bf09a751a4e043fc6bd01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=782170, ip=192.168.100.251, actor_id=13d69bf09a751a4e043fc6bd01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7a7c974cae80>)\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=782170)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:00:02,666 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 45.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:00:02,666 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m INFO 2024-11-13 09:00:04,776 proxy 192.168.100.251 proxy.py:1128 - Proxy actor a6a51a74032daa64ba4fcaa401000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=782986, ip=192.168.100.251, actor_id=a6a51a74032daa64ba4fcaa401000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x704af7f8ef40>)\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=782986)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:00:52,684 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 50.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:00:52,685 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m INFO 2024-11-13 09:00:56,180 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 4833fcd2652fd6d5de4bc6fd01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=784074, ip=192.168.100.251, actor_id=4833fcd2652fd6d5de4bc6fd01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x77512000eeb0>)\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=784074)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:01:47,884 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 55.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:01:47,884 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m INFO 2024-11-13 09:01:49,813 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 861fef6375f2fdf0bc73973601000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=785440, ip=192.168.100.251, actor_id=861fef6375f2fdf0bc73973601000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7611da04af70>)\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=785440)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:02:47,975 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 60.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:02:47,975 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m INFO 2024-11-13 09:02:49,673 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 501dd8708ee8695b7c6d0cf301000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=786635, ip=192.168.100.251, actor_id=501dd8708ee8695b7c6d0cf301000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x74478810aee0>)\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=786635)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:03:52,996 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 65.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:03:52,996 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m INFO 2024-11-13 09:03:54,791 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 979ed0d6476b648a0a33e69201000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=787914, ip=192.168.100.251, actor_id=979ed0d6476b648a0a33e69201000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x769cca10af40>)\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=787914)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:05:03,107 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 70.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:05:03,107 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m INFO 2024-11-13 09:05:04,496 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 7f08e807df9aadf77716d0b001000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=789143, ip=192.168.100.251, actor_id=7f08e807df9aadf77716d0b001000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x74fdef58ef40>)\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=789143)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:06:18,126 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 75.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:06:18,126 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m INFO 2024-11-13 09:06:19,489 proxy 192.168.100.251 proxy.py:1128 - Proxy actor b3fca42abba8f6a6228b31fe01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=790453, ip=192.168.100.251, actor_id=b3fca42abba8f6a6228b31fe01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7cb12b50aeb0>)\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=790453)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:07:38,176 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 80.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:07:38,176 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m INFO 2024-11-13 09:07:39,545 proxy 192.168.100.251 proxy.py:1128 - Proxy actor c2714c0a51eaee12c7a14e5c01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=791868, ip=192.168.100.251, actor_id=c2714c0a51eaee12c7a14e5c01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7dcafd6caee0>)\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=791868)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:09:03,278 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 85.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:09:03,279 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m INFO 2024-11-13 09:09:04,621 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 422bcf840335c0a75e76529601000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=793337, ip=192.168.100.251, actor_id=422bcf840335c0a75e76529601000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x74e7702caf10>)\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=793337)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:10:33,311 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 90.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:10:33,311 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m INFO 2024-11-13 09:10:34,683 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 71ae1ab317e3247ca3520f3601000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=794940, ip=192.168.100.251, actor_id=71ae1ab317e3247ca3520f3601000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x749f53ecaeb0>)\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=794940)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:12:08,364 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 95.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:12:08,365 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m INFO 2024-11-13 09:12:09,821 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 2652b13b791a3376215bb9c901000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=796568, ip=192.168.100.251, actor_id=2652b13b791a3376215bb9c901000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x79f95800eeb0>)\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=796568)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:13:48,404 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 100.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:13:48,404 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m INFO 2024-11-13 09:13:49,770 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 259dabf95370859a3ba079b301000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=798327, ip=192.168.100.251, actor_id=259dabf95370859a3ba079b301000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7efbe96cae80>)\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=798327)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:15:33,421 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 105.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:15:33,422 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m INFO 2024-11-13 09:15:34,814 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 08af3a65ebe9a99b9c90f54701000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=800124, ip=192.168.100.251, actor_id=08af3a65ebe9a99b9c90f54701000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7efe9578ee50>)\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=800124)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:17:23,496 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 110.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:17:23,497 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m INFO 2024-11-13 09:17:24,913 proxy 192.168.100.251 proxy.py:1128 - Proxy actor f9f9a51dd61c0f6bac0fc20701000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=802019, ip=192.168.100.251, actor_id=f9f9a51dd61c0f6bac0fc20701000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x73eff7e49f10>)\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m [2024-11-13 09:17:24,992 E 802019 802019] logging.cc:104: Stack trace: \n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m  /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x10051da) [0x73f00d0051da] ray::operator<<()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x1007918) [0x73f00d007918] ray::TerminateHandler()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae20c) [0x73f00bcae20c]\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae277) [0x73f00bcae277]\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x7e5260) [0x73f00c7e5260] std::thread::_State_impl<>::~_State_impl()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x6405aa) [0x73f00c6405aa] std::_Sp_counted_base<>::_M_release()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x7ce262) [0x73f00c7ce262] std::_Sp_counted_ptr_inplace<>::_M_dispose()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x6405aa) [0x73f00c6405aa] std::_Sp_counted_base<>::_M_release()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x7056c2) [0x73f00c7056c2] std::default_delete<>::operator()()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(_ZN3ray4core10CoreWorkerD1Ev+0xeb) [0x73f00c77766b] ray::core::CoreWorker::~CoreWorker()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x6405aa) [0x73f00c6405aa] std::_Sp_counted_base<>::_M_release()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(_ZN3ray4core21CoreWorkerProcessImpl26RunWorkerTaskExecutionLoopEv+0x134) [0x73f00c7b57e4] ray::core::CoreWorkerProcessImpl::RunWorkerTaskExecutionLoop()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(_ZN3ray4core17CoreWorkerProcess20RunTaskExecutionLoopEv+0x1d) [0x73f00c7b58ed] ray::core::CoreWorkerProcess::RunTaskExecutionLoop()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x5b2747) [0x73f00c5b2747] __pyx_pw_3ray_7_raylet_10CoreWorker_7run_task_loop()\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor() [0x519465]\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(_PyEval_EvalFrameDefault+0x6ce) [0x503fee] _PyEval_EvalFrameDefault\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(_PyFunction_Vectorcall+0x10f) [0x51491f] _PyFunction_Vectorcall\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(_PyEval_EvalFrameDefault+0x6ce) [0x503fee] _PyEval_EvalFrameDefault\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(_PyEval_EvalCodeWithName+0x2fa) [0x50275a] _PyEval_EvalCodeWithName\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(PyEval_EvalCode+0x27) [0x5d6ca7] PyEval_EvalCode\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor() [0x5f7b75]\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor() [0x5f6b83]\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor() [0x5f5c26]\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(PyRun_SimpleFileExFlags+0x197) [0x5f58d7] PyRun_SimpleFileExFlags\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(Py_RunMain+0x2c1) [0x5f2a71] Py_RunMain\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(Py_BytesMain+0x2d) [0x5cad7d] Py_BytesMain\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x73f00e029d90]\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x73f00e029e40] __libc_start_main\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m ray::ProxyActor(_start+0x25) [0x5cac75] _start\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m \n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m *** SIGABRT received at time=1731464244 on cpu 1 ***\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m PC: @     0x73f00e0969fc  (unknown)  pthread_kill\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m     @     0x73f00e042520  (unknown)  (unknown)\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m [2024-11-13 09:17:24,993 E 802019 802019] logging.cc:361: *** SIGABRT received at time=1731464244 on cpu 1 ***\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m [2024-11-13 09:17:24,993 E 802019 802019] logging.cc:361: PC: @     0x73f00e0969fc  (unknown)  pthread_kill\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m [2024-11-13 09:17:24,993 E 802019 802019] logging.cc:361:     @     0x73f00e042520  (unknown)  (unknown)\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m Fatal Python error: Aborted\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m \n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m Stack (most recent call first):\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_private/worker.py\", line 847 in main_loop\n",
      "\u001b[36m(ProxyActor pid=802019)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_private/workers/default_worker.py\", line 282 in <module>\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:17:25,043 controller 777951 proxy_state.py:526 - Unexpected actor death when checking readiness of proxy on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m NoneType: None\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:17:25,043 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:19:25,065 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 120.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:19:25,065 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m INFO 2024-11-13 09:17:26,607 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 92781a1c44e5b07f0014870c01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=802108, ip=192.168.100.251, actor_id=92781a1c44e5b07f0014870c01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x779d6be4ae80>)\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=802108)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m \n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m INFO 2024-11-13 09:19:26,420 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 2ec925b5e0f63de30ae8808001000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=804714, ip=192.168.100.251, actor_id=2ec925b5e0f63de30ae8808001000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7be5f0c4af10>)\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=804714)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:21:30,079 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 125.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:21:30,079 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m INFO 2024-11-13 09:21:31,397 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 0fe5060dba66f0af93e9f13401000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=806864, ip=192.168.100.251, actor_id=0fe5060dba66f0af93e9f13401000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x714aba0c9f10>)\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=806864)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:23:40,128 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 130.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:23:40,128 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m INFO 2024-11-13 09:23:41,467 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 01ed9a7ebbdda1594b56156501000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=809126, ip=192.168.100.251, actor_id=01ed9a7ebbdda1594b56156501000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x75deeeb8eeb0>)\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=809126)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:25:55,160 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 135.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:25:55,161 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m INFO 2024-11-13 09:25:56,474 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 4ba7e502322485360b45eafa01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=811467, ip=192.168.100.251, actor_id=4ba7e502322485360b45eafa01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7f11b20caee0>)\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=811467)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:28:15,261 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 140.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:28:15,261 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m INFO 2024-11-13 09:28:16,630 proxy 192.168.100.251 proxy.py:1128 - Proxy actor a855eec913eaf1b29b87d25901000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=813926, ip=192.168.100.251, actor_id=a855eec913eaf1b29b87d25901000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x725e7becaf10>)\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=813926)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:30:40,359 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 145.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:30:40,360 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m INFO 2024-11-13 09:30:43,099 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 48a5c1acfa2fd8485d8c621901000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=816563, ip=192.168.100.251, actor_id=48a5c1acfa2fd8485d8c621901000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x77ffe564aee0>)\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:30:43,238 controller 777951 proxy_state.py:526 - Unexpected actor death when checking readiness of proxy on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m NoneType: None\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m \n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:30:43,239 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m [2024-11-13 09:30:43,218 E 816563 816563] logging.cc:104: Stack trace: \n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m  /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x10051da) [0x77fff38051da] ray::operator<<()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x1007918) [0x77fff3807918] ray::TerminateHandler()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x7e5260) [0x77fff2fe5260] std::thread::_State_impl<>::~_State_impl()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x6405aa) [0x77fff2e405aa] std::_Sp_counted_base<>::_M_release()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x7ce262) [0x77fff2fce262] std::_Sp_counted_ptr_inplace<>::_M_dispose()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x6405aa) [0x77fff2e405aa] std::_Sp_counted_base<>::_M_release()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x7056c2) [0x77fff2f056c2] std::default_delete<>::operator()()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(_ZN3ray4core10CoreWorkerD1Ev+0xeb) [0x77fff2f7766b] ray::core::CoreWorker::~CoreWorker()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(+0x6405aa) [0x77fff2e405aa] std::_Sp_counted_base<>::_M_release()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(_ZN3ray4core21CoreWorkerProcessImpl26RunWorkerTaskExecutionLoopEv+0x134) [0x77fff2fb57e4] ray::core::CoreWorkerProcessImpl::RunWorkerTaskExecutionLoop()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_raylet.so(_ZN3ray4core17CoreWorkerProcess20RunTaskExecutionLoopEv+0x1d) [0x77fff2fb58ed] ray::core::CoreWorkerProcess::RunTaskExecutionLoop()\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor() [0x519465]\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(_PyEval_EvalFrameDefault+0x6ce) [0x503fee] _PyEval_EvalFrameDefault\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(_PyFunction_Vectorcall+0x10f) [0x51491f] _PyFunction_Vectorcall\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(_PyEval_EvalFrameDefault+0x6ce) [0x503fee] _PyEval_EvalFrameDefault\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(_PyEval_EvalCodeWithName+0x2fa) [0x50275a] _PyEval_EvalCodeWithName\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(PyEval_EvalCode+0x27) [0x5d6ca7] PyEval_EvalCode\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor() [0x5f7b75]\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor() [0x5f6b83]\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor() [0x5f5c26]\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(PyRun_SimpleFileExFlags+0x197) [0x5f58d7] PyRun_SimpleFileExFlags\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(Py_RunMain+0x2c1) [0x5f2a71] Py_RunMain\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(Py_BytesMain+0x2d) [0x5cad7d] Py_BytesMain\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x77fff4829e40] __libc_start_main\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m ray::ProxyActor(_start+0x25) [0x5cac75] _start\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m *** SIGABRT received at time=1731465043 on cpu 2 ***\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m PC: @     0x77fff48969fc  (unknown)  pthread_kill\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m     @     0x77fff4842520  (unknown)  (unknown)\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m [2024-11-13 09:30:43,219 E 816563 816563] logging.cc:361: *** SIGABRT received at time=1731465043 on cpu 2 ***\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m [2024-11-13 09:30:43,219 E 816563 816563] logging.cc:361: PC: @     0x77fff48969fc  (unknown)  pthread_kill\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m [2024-11-13 09:30:43,219 E 816563 816563] logging.cc:361:     @     0x77fff4842520  (unknown)  (unknown)\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m Fatal Python error: Aborted\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m Stack (most recent call first):\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_private/worker.py\", line 847 in main_loop\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/_private/workers/default_worker.py\", line 282 in <module>\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:33:18,291 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 155.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:33:18,292 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m INFO 2024-11-13 09:30:45,458 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 30df7b1e97d28f73045c97d401000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=816623, ip=192.168.100.251, actor_id=30df7b1e97d28f73045c97d401000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x715bbd64af40>)\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=816623)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ProxyActor pid=816563)\u001b[0m \u001b[32m [repeated 6x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m INFO 2024-11-13 09:33:22,036 proxy 192.168.100.251 proxy.py:1128 - Proxy actor ef5a59a0decf0b1acb45786001000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=819881, ip=192.168.100.251, actor_id=ef5a59a0decf0b1acb45786001000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x782510d8df10>)\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=819881)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:35:58,429 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 160.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:35:58,429 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m INFO 2024-11-13 09:36:00,436 proxy 192.168.100.251 proxy.py:1128 - Proxy actor bedb3f6b52171e07b125d5d101000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=823216, ip=192.168.100.251, actor_id=bedb3f6b52171e07b125d5d101000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x78aa4970adc0>)\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=823216)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:38:43,510 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 165.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:38:43,510 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m INFO 2024-11-13 09:38:45,423 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 19d319025f9b1d9cc90ff42901000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=826460, ip=192.168.100.251, actor_id=19d319025f9b1d9cc90ff42901000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x73657028aeb0>)\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=826460)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:41:33,572 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 170.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:41:33,572 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m INFO 2024-11-13 09:41:34,989 proxy 192.168.100.251 proxy.py:1128 - Proxy actor 84e4d6c7e6d4d0406a689e6c01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=829524, ip=192.168.100.251, actor_id=84e4d6c7e6d4d0406a689e6c01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x7b2ce0ccaf10>)\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 444, in result\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=829524)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m WARNING 2024-11-13 09:44:28,596 controller 777951 proxy_state.py:537 - Didn't receive ready check response for proxy e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43 after 175.0s.\n",
      "\u001b[36m(ServeController pid=777951)\u001b[0m INFO 2024-11-13 09:44:28,597 controller 777951 proxy_state.py:805 - Proxy on node 'e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43' UNHEALTHY. Shutting down the unhealthy proxy and starting a new one.\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m INFO 2024-11-13 09:44:30,040 proxy 192.168.100.251 proxy.py:1128 - Proxy actor d7685598aff2c80e2dd6df4b01000000 starting on node e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43.\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SERVE_CONTROLLER_ACTOR:SERVE_PROXY_ACTOR-e51ca75891f8578bf0b66770221369bfe033829266d37e744c593f43:ProxyActor.__init__()\u001b[39m (pid=832849, ip=192.168.100.251, actor_id=d7685598aff2c80e2dd6df4b01000000, repr=<ray.serve._private.proxy.ProxyActor object at 0x71662cd0af70>)\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 437, in result\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m     return self.__get_result()\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m   File \"/usr/lib/python3.8/concurrent/futures/_base.py\", line 389, in __get_result\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m     raise self._exception\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m   File \"/home/danielpepuho/Desktop/Github/pra-ta/.venv/lib/python3.8/site-packages/ray/serve/_private/proxy.py\", line 1202, in __init__\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m     self.wrapped_http_proxy, **middleware.options\n",
      "\u001b[36m(ProxyActor pid=832849)\u001b[0m AttributeError: 'Middleware' object has no attribute 'options'\n"
     ]
    }
   ],
   "source": [
    "import asyncio\n",
    "import logging\n",
    "from fastapi import FastAPI, WebSocket, WebSocketDisconnect\n",
    "from transformers import AutoModelForCausalLM, AutoTokenizer, TextIteratorStreamer\n",
    "from ray import serve\n",
    "\n",
    "# Set up logging\n",
    "logger = logging.getLogger(\"ray.serve\")\n",
    "\n",
    "# Initialize FastAPI app\n",
    "app = FastAPI()\n",
    "\n",
    "@serve.deployment\n",
    "@serve.ingress(app)\n",
    "class Chatbot:\n",
    "    def __init__(self, model_id: str):\n",
    "        self.loop = asyncio.get_running_loop()\n",
    "        self.model_id = model_id\n",
    "        self.model = AutoModelForCausalLM.from_pretrained(self.model_id)\n",
    "        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id)\n",
    "\n",
    "    @app.websocket(\"/chat\")\n",
    "    async def chat(self, websocket: WebSocket):\n",
    "        await websocket.accept()\n",
    "        try:\n",
    "            while True:\n",
    "                data = await websocket.receive_text()\n",
    "                logger.info(f\"Received message: {data}\")\n",
    "                response = await self.generate_response(data)\n",
    "                await websocket.send_text(response)\n",
    "        except WebSocketDisconnect:\n",
    "            logger.info(\"Client disconnected\")\n",
    "\n",
    "    async def generate_response(self, prompt: str) -> str:\n",
    "        inputs = self.tokenizer(prompt, return_tensors=\"pt\")\n",
    "        streamer = TextIteratorStreamer(self.tokenizer)\n",
    "\n",
    "        # Generate response in a background thread\n",
    "        await self.loop.run_in_executor(None, self.model.generate, **inputs, streamer=streamer)\n",
    "\n",
    "        # Collect generated tokens\n",
    "        response = \"\"\n",
    "        for token in streamer:\n",
    "            response += token\n",
    "\n",
    "        return response\n",
    "\n",
    "# Bind and run the deployment\n",
    "chatbot_app = Chatbot.bind(\"microsoft/DialoGPT-small\")  # Replace with your model ID\n",
    "serve.run(chatbot_app)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.20"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
